name: CreateAndPublishClientPackage

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '10.x'                # set this to the node version to use
  CLIENT_PACKAGE_NAME: '@gjv/moodful-api-client'
  PACKAGE_FOLDER: './client-package'
  OPENAPI_SPECIFICATION_LOCATION: '..\..\Swagger\openapi.spec.json'
  BUMP_KIND: 'patch'

jobs:
  create-and-publish:
    name: Create and Publish Client Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Create Client Package
      shell: pwsh
      run: ../../Scripts/CreateClientPackage.ps1 -packageName ${{ env.CLIENT_PACKAGE_NAME }} -bumpKind ${{ env.BUMP_KIND }} -packageFolder ${{ env.PACKAGE_FOLDER }}
    - name: Change Current Location
      shell: pwsh
      run: Push-Location ${{ env.PACKAGE_FOLDER }}
    - name: install
      run: npm install
    - name: build
      run: npm run build
    - name: publish
      run: npm publish --access public
