name: CreateAndPublishClientPackage

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '10.x'                # set this to the node version to use
  CLIENT_PACKAGE_NAME: '@gjv/moodful-api-client'
  CLIENT_PACKAGE_FOLDER: './client-package'
  OPENAPI_SPECIFICATION_LOCATION: '../../Swagger/openapi.spec.json'
  BUMP_KIND: 'patch'

jobs:
  create-and-publish:
    name: Create and Publish Client Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    # - run: npm install -g @openapitools/openapi-generator-cli@latest
    - name: Create client package
      shell: pwsh
      run: |
            $nextVersion = ../../Scripts/BumpNpmPackageVersion.ps1 -packageName ${{ env.CLIENT_PACKAGE_NAME }} -bumpKind ${{ env.BUMP_KIND }}
            ../../Scripts/GenerateClientPackage.ps1 -specificationFileLocation ${{ env.OPENAPI_SPECIFICATION_LOCATION }} -outputDirectory ${{ env.CLIENT_PACKAGE_FOLDER }} -clientName ${{ env.CLIENT_PACKAGE_NAME }} -clientVersion $nextVersion
            ../../Scripts/PrepareClientPackage.ps1 -workingDirectory ${{ env.CLIENT_PACKAGE_FOLDER }}
            Write-Host ("`n`n The client package was successfully created in folder '{0}'. `n`n " -f $packageFolder)
    - name: Change Current Location to ${{ env.CLIENT_PACKAGE_FOLDER }}
      shell: pwsh
      run: Push-Location ${{ env.CLIENT_PACKAGE_FOLDER }}
    - run: npm install
    - run: npm run build
    - run: npm publish --access public
